#!/bin/bash
# Install the multi-camera variant alongside the original single-camera service.

set -e
INSTALL_DIR="/opt/prusa-cam-multi"
CONFIG_FILE="/etc/prusa_cam-multi.conf"
BASE_PORT=8090
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ $EUID -ne 0 ]]; then
    echo "Run this installer as root: sudo bash install-multi.sh"; exit 1
fi

echo "Prusa Connect multi-camera setup"
echo "Installing to $INSTALL_DIR; streams will use ports starting at $BASE_PORT."
apt-get update -qq
apt-get install -y -qq curl v4l-utils python3 ffmpeg

mkdir -p "$INSTALL_DIR/scripts"
cp "$SCRIPT_DIR/scripts/detect_cameras.sh" "$SCRIPT_DIR/scripts/stream_server.sh" \
   "$SCRIPT_DIR/scripts/multi_stream_server.sh" \
   "$SCRIPT_DIR/scripts/multi_prusa_connect_upload.sh" "$INSTALL_DIR/scripts/"
chmod +x "$INSTALL_DIR/scripts/"*.sh

source "$INSTALL_DIR/scripts/detect_cameras.sh"
mapfile -t cameras < <({ detect_rpi_cameras; detect_usb_cameras; })
if [[ ${#cameras[@]} -eq 0 ]]; then
    echo "ERROR: no cameras detected."; exit 1
fi

echo "Detected ${#cameras[@]} camera(s). Each camera will be configured in order."
echo ""
{
    echo "# Generated by install-multi.sh on $(date)"
    echo "CAMERA_COUNT=${#cameras[@]}"
    echo "UPLOAD_INTERVAL=10"
    echo "STREAM_WIDTH=1280"
    echo "STREAM_HEIGHT=720"
    echo ""
} > "$CONFIG_FILE"

for index in "${!cameras[@]}"; do
    number=$((index + 1))
    camera="${cameras[$index]}"
    type=$(echo "$camera" | cut -d: -f1)
    id=$(echo "$camera" | cut -d: -f2)
    name=$(echo "$camera" | cut -d: -f3-)
    device=""
    [[ "$type" == "USB" ]] && device="$id"
    port=$((BASE_PORT + index))

    echo "Camera $number/${#cameras[@]}: $name"
    echo "  Stream: http://<raspberry-pi-ip>:$port"
    while true; do
        read -r -p "  Enter the Prusa Connect token for this camera: " token < /dev/tty
        [[ -n "$token" ]] && break
        echo "  Token cannot be empty."
    done
    fingerprint=$(cat /proc/sys/kernel/random/uuid)
    printf 'CAMERA_%s_TYPE=%q\nCAMERA_%s_ID=%q\nCAMERA_%s_DEVICE=%q\nCAMERA_%s_NAME=%q\nCAMERA_%s_PORT=%q\nCAMERA_%s_FINGERPRINT=%q\nCAMERA_%s_TOKEN=%q\n\n' \
        "$number" "$type" "$number" "$id" "$number" "$device" "$number" "$name" \
        "$number" "$port" "$number" "$fingerprint" "$number" "$token" >> "$CONFIG_FILE"
    echo ""
done
chmod 600 "$CONFIG_FILE"

cat > /etc/systemd/system/camera-stream-multi.service <<'EOF'
[Unit]
Description=Prusa Connect Multi-Camera MJPEG Stream Servers
After=network.target
[Service]
Type=simple
ExecStart=/opt/prusa-cam-multi/scripts/multi_stream_server.sh
Restart=always
RestartSec=5
User=root
StandardOutput=journal
StandardError=journal
SyslogIdentifier=camera-stream-multi
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=read-only
ReadWritePaths=/tmp
[Install]
WantedBy=multi-user.target
EOF

cat > /etc/systemd/system/prusa-connect-upload-multi.service <<'EOF'
[Unit]
Description=Prusa Connect Multi-Camera Upload Service
After=network-online.target camera-stream-multi.service
Wants=network-online.target
[Service]
Type=simple
ExecStart=/opt/prusa-cam-multi/scripts/multi_prusa_connect_upload.sh
Restart=always
RestartSec=10
User=root
StandardOutput=journal
StandardError=journal
SyslogIdentifier=prusa-connect-upload-multi
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=read-only
ReadWritePaths=/tmp
[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now camera-stream-multi.service
systemctl enable --now prusa-connect-upload-multi.service

echo ""
echo "Multi-camera installation complete."
echo "Streams: http://<raspberry-pi-ip>:$BASE_PORT through port $((BASE_PORT + ${#cameras[@]} - 1))"
echo "Config: $CONFIG_FILE"
echo "Logs: journalctl -u camera-stream-multi -f"
